# Generated by Django 4.0.5 on 2022-06-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
    ]
