# Generated by Django 4.0.5 on 2022-07-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0003_rename_name_tag_tag_remove_tag_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
