services:
  web-app:
    build:
      context: .

    volumes:
      - ./my_django/:/PycharmProjects/django_tms/
#      - ./my_django/media/:/my_django/media/
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - database
  database:
   image: postgres:14.6-alpine
   environment:
     - POSTGRES_DB=dbname
     - POSTGRES_USER=dbuser
     - POSTGRES_PASSWORD=pass

# миграции делаем в консоли
#docker-compose run --rm web-app sh -c "python manage.py migrate"