# Generated by Django 4.0.4 on 2022-04-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0002_post_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
