# Generated by Django 4.0.4 on 2022-05-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0003_alter_postimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
