# Generated by Django 4.0.4 on 2022-05-05 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0006_alter_post_options_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Великие футболисты'},
        ),
        migrations.AddField(
            model_name='post',
            name='nationality',
            field=models.TextField(default=django.utils.timezone.now, max_length=256, verbose_name='Национальность'),
            preserve_default=False,
        ),
    ]
