# Generated by Django 4.0.4 on 2022-05-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0007_alter_post_options_post_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Пост'),
        ),
    ]
