# Generated by Django 4.0.4 on 2022-05-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0008_remove_post_text_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at', 'title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Великие '
                                                                                                         'футболисты'},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='publication_app'
                                                                                               '.category'),
        ),
    ]
