# Generated by Django 4.0.4 on 2022-05-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0009_category_alter_post_options_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Великие футболисты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
    ]
