# Generated by Django 4.0.4 on 2022-05-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0010_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Спортсмены'},
        ),
    ]
