# Generated by Django 4.0.4 on 2022-05-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0012_alter_tag_options_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='publication_app.tag'),
        ),
    ]
