# Generated by Django 4.0.5 on 2022-06-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0017_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
