# Generated by Django 4.0.5 on 2022-06-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0003_rename_name_tag_tag_remove_tag_posts'),
        ('publication_app', '0019_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag_post', to='tags_app.tag'),
        ),
    ]
