# Generated by Django 4.0.6 on 2022-07-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_comments', models.CharField(max_length=256, verbose_name='Комментарий')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
