# Generated by Django 4.0.6 on 2022-07-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0002_comments_updated_at_alter_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text_comments',
            field=models.CharField(max_length=256, verbose_name='Комментарий'),
        ),
    ]
