# Generated by Django 4.0.6 on 2022-07-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.TextField(blank=True, max_length=4096, null=True, verbose_name='О себе')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на GitHub')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['id'],
            },
        ),
    ]
