# Generated by Django 4.0.4 on 2022-06-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Друзья', 'verbose_name_plural': 'Друзья'},
        ),
    ]
