# Generated by Django 4.0.4 on 2022-06-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0002_alter_friend_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='users',
            new_name='user',
        ),
    ]
