# Generated by Django 4.0.6 on 2022-07-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0006_friend_created_at_friend_friendship_result_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together=set(),
        ),
    ]
